env_files = ["./neardev/dev-account.env"]

extend = "../Makefile.toml"

[env]
PACKAGE = "oysterpack_smart_stake"

[tasks.build-wasm]
private = true
command = "cargo"
args = ["build", "--target", "wasm32-unknown-unknown", "--release"]


[tasks.build]
description = "Optimizes the wasm file for small size"
category = "Build"
command = "wasm-opt"
args = ["../target/wasm32-unknown-unknown/release/${PACKAGE}.wasm", "-Oz", "-o", "../target/wasm32-unknown-unknown/release/${PACKAGE}.wasm"]
dependencies = ["build-wasm"]

[tasks.wasm-ls]
script_runner = "@duckscript"
script = '''
ls -la ../target/wasm32-unknown-unknown/release/${PACKAGE}.wasm
'''

[tasks.near-dev-deploy]
command = "near"
args = ["dev-deploy", "../target/wasm32-unknown-unknown/release/${PACKAGE}.wasm"]
dependencies = ["wasm-opt"]

[tasks.near-state]
command = "near"
args = ["state", "${CONTRACT_NAME}"]
dependencies = ["wasm-opt"]

[tasks.near-deploy-init]
script_runner = "@duckscript"
script = '''
export NEAR_ENV=testnet
'''